### ISSUE TITLE
Support code syntax highlighting

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#108]
There has been requests for syntax highlighting in PDF.

These two components seem to be somewhat promising:
* https://github.com/codelibs/jhighlight
* https://github.com/pgfearo/xmlspectrum

**Comment by Intelligent2013** [comment]
To do: proof of concept
- JVM has JavaScript engine Nashorn  (https://www.baeldung.com/java-nashorn)
- there are a few JS syntax highlighters (highlightjs.org, prismjs.com) which support a lot of languages
- need to try 
  - call JS highlighter from Java
  - add CSS properties from .css to `span` element as attributes (to process via xslt)
  - process formatted string (with attributes `span` elements) in xslt to render in PDF

First attempt to call highlight.js from Java:
```
Exception in thread "main" javax.script.ScriptException: SyntaxError: file:/D:/Metanorma/CallJS/target/classes/highlight.min.js:7:48 Expected an operand but found )
return e instanceof Map?e.clear=e.delete=e.set=()=>{
                                                ^ in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
```

It seems the reason in non-compatibility in Nashorn (ECMAScript 5.1, 2011 year) vs. highlight.js JS versions.
From https://www.baeldung.com/java-nashorn#language-extensions:
```
Nashorn is targeting ECMAScript 5.1 ...
```
Will try to re-build for old version...

**Comment by Intelligent2013** [comment]
Nashorn deprecated and removed from Java 15: https://openjdk.java.net/jeps/372
GraalJS should be used instead of.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 ! Could you use a new Pull Request to develop this new functionality?

**Comment by Intelligent2013** [comment]
> Thanks @Intelligent2013 ! Could you use a new Pull Request to develop this new functionality?

@ronaldtse ok, done.
How would you like to apply syntax highlighting feature?
1. always for all offices
2. always for selected offices only
3. for concrete document

**Comment by ronaldtse** [comment]
> How would you like to apply syntax highlighting feature?
> 
> 1. always for all offices
> 2. always for selected offices only
> 3. for concrete document

The syntax highlighting should be applied to all `sourcecode` blocks with a designated type (e.g. `yaml` or `json` or `c++` etc).

Not sure what you mean by "office"?

**Comment by Intelligent2013** [comment]
> Not sure what you mean by "office"?

@ronaldtse I mean, for instance, turn on syntax hightlighting for OGC, BSI documents only.

**Comment by ronaldtse** [comment]
@Intelligent2013 let's make it a parameter/option so that different flavors can turn syntax highlighting on or off?

**Comment by Intelligent2013** [comment]
Done:
- syntax highlight feature based on highlight.js library (https://highlightjs.org/), mn2pdf supports all 196 languages 
- command-line parameter `--syntax-highlight` added for mn2pdf. It turns on this feature.
- dynamically fetch highlight.js on build
- highlight styles (see _to do_ below) based on Github styles (see examples on https://highlightjs.org/static/demo/,click Github at the left pane Themes)

Rendered PDF examples:
- ruby (ISO rice-en)
![image](https://user-images.githubusercontent.com/5559926/150838114-77eb4102-2d74-48f5-a038-192105b06585.png)

- xml
![image](https://user-images.githubusercontent.com/5559926/150838434-2aa2d65a-8a86-4ed0-9b64-964f9afb3cda.png)

- adoc
![image](https://user-images.githubusercontent.com/5559926/150839549-5a71d704-a9fb-49e9-81d8-76a03dbeaa0d.png)


Next task: xslt uses hard-coded styles (manually converted from CSS) for highlighting. I would like to find a solution to apply styles to each highlight element `span` (similar to the browser JS method `window.getComputerStyle`) for processing them from xslt on fly. I.e. instead of
```xml
css styles(classes) in external .css file
...
<span class="hljs-tagname">text</span>
```
should be
```xml
<span style="color:#a561232; font-weight:bold">text</span>
```
But I didn't find a clear solution yet...

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 ! If possible let's merge this first and have the XSLT processing update in a separate issue? Some people are eager to use this new functionality. Thanks 😉

**Comment by Intelligent2013** [comment]
Source code syntax highlighting feature available in https://github.com/metanorma/mn2pdf/releases/tag/v1.41
```
java -Xss5m -Xmx2048m -jar mn2pdf-1.41.jar --xml-file ... --syntax-highlight
```

**Comment by Intelligent2013** [comment]
`--syntax-highlight` feature disabled in XSLT. Now, the sourcecode highlighting controlled in `/misc-container/source-highlighter-css` and `sourcecode/span`. See https://github.com/metanorma/metanorma-ogc/issues/478.
