### ISSUE TITLE
Differentiate File Annotation and Javascript link to the embedded file

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mn2pdf#283]
Currently (https://github.com/metanorma/mn2pdf/issues/267), the link prefixed by `url(embedded-file:` process as File annotation (with PaperClip icon).
But BIPM brochure should allow to open the MathML file by just clicking on the math formula.
I.e. need to support both links to the embedded file:
- current functionality by JavaScript function
- File annotation link

**Comment by petervwyatt** [comment]
Just a comment / FYI: MathML can serve multiple purposes in PDF:

* they may be needed for accessibility (e.g. supporting PDF/UA-1 conformance) - see this [LaTeX discussion](https://github.com/latex3/tagging-project/discussions/82) if you want some actual examples of PDF/UA-1 with MathML (or this [different LaTeX discussion](https://github.com/latex3/tagging-project/discussions/72) for PDF 2.0 and PDF/UA-2).

* standards authors may also want to have the MathML as visible downloadable embedded files / attachments so all(!) users can then "do math stuff" with the semantically rich data.

* reuse of the math (i.e. so that copy'n'paste from PDF back into MS Word, for example, retains all the math-ness and ends up in Word's equation editor) is best when the MathML is associated with the logical structure (but success very much depends on the PDF app being used). You can experiment with the LaTeX examples I referenced above.

Of course, the same embedded file stream data that is the MathML can be reused for all purposes (so only embed once and reference multiple times).

**Comment by Intelligent2013** [comment]
@petervwyatt very interesting approach, thanks! I'll look at this.

**Comment by Intelligent2013** [comment]
> current functionality by JavaScript function

This functionality restored for BIPM brochure.
I have to review this feature after analyze the cases from https://github.com/metanorma/mn2pdf/issues/283#issuecomment-2369843691.

**Comment by Intelligent2013** [comment]
Done in https://github.com/metanorma/mn2pdf/releases/tag/v2.01.

**Comment by ronaldtse** [comment]
@petervwyatt we published a blog post about PDF math here if you recall, so we are always interested in new / better approaches:
* https://www.metanorma.org/blog/2021-08-26-pdf-accessibility-for-math-formulas/
