### ISSUE TITLE
Misplaced prefatory section in OGC document

### ISSUE THREAD

**Issue by manuel489** [metanorma/mn2pdf#60]
*In relation to https://github.com/metanorma/mn-native-pdf/issues/89*

In 14-065r2, "Keywords" prefatory section is misplaced in PDF output. (It should be after "Abstract" section.)

DOC output:
![issue1-doc](https://user-images.githubusercontent.com/33627611/106395466-c985b180-63d8-11eb-9f57-7ba421434c8b.PNG)

PDF output:
![issue1-pdf](https://user-images.githubusercontent.com/33627611/106395459-c5599400-63d8-11eb-9b83-5baef15add22.PNG)

I'm not sure whether this is a general case (applicable to all the OGC documents) or particular to 14-065r2.

UPDATE:
It is general. 15-104r4 also has the same issue.

**Comment by ronaldtse** [comment]
I think this order should be defined in presentation XML: ping @opoudjis @Intelligent2013

**Comment by Intelligent2013** [comment]
@manuel489 this issue was fixed a few month ago. Looks like you use very old stylesheet or pdf. How did you get the PDF?

I don't see any issues in Keyword displaying (https://github.com/metanorma/mn-samples-ogc/tree/gh-pages/documents)
![изображение](https://user-images.githubusercontent.com/5559926/106450190-e6cc8580-6495-11eb-81e7-a3e02598c8e1.png)

![изображение](https://user-images.githubusercontent.com/5559926/106450291-08c60800-6496-11eb-9634-68b35e51c455.png)

**Comment by manuel489** [comment]
@Intelligent2013,
Oh... I got them by compilation. I guess those are not the ones that we should review.
So, we are good here?

**Comment by Intelligent2013** [comment]
@manuel489  I don't figure out how to compile ogc documents for mn-samples-ogc repo and can't check the resulted PDF.
I run make publish on my Ubuntu and get the error:
```
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
```

```
yq -V
yq version 4.3.2
```
but looks like the command `r` works in v3 only... It's a puzzle for me.

**Comment by Intelligent2013** [comment]
@manuel489 `bundle exec metanorma -t ogc -x pdf,doc sources/14-065r2/document.adoc` creates correct PDF.
Please run `bundle update` to install latest modules.

**Comment by manuel489** [comment]
Yeah... Because I had the latest version of mn2pdf I thought 
that was enough for generating the PDFs. But it was not.
All is good now. This issue is fixed.
Thanks @Intelligent2013!
