### ISSUE TITLE
Move MN_PDF_FONT_PATH environment variable inside mn2pdf Java code

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn2pdf#8]
> We can pass font directory via argument or via MN_PDF_FONT_PATH environment variable. I prefer via environment variable, because we use it also in other scripts for font installation process.

@Intelligent2013 we are going to move the font installation process into Metanorma proper, so it the usage of this environment variable `MN_PDF_FONT_PATH ` will be de-coupled. We don't need to keep it.

> @Intelligent2013 as far as I understood pdf_fonts_config.xml will comes from metanorma-* processors (i.e. metanorma-iso, metanorma-ogc and so on), is that true?

I'd rather we internalize pdf_fonts_config.xml inside `mn2pdf`? metanorma-* can provide the font path to mn2pdf?

_Originally posted by @ronaldtse in https://github.com/metanorma/mn2pdf/pull/5#issuecomment-599965591_

**Comment by ronaldtse** [comment]
From @Intelligent2013 
> @CAMOBAP795 Hmm... I don't sure. I know only that it uses in 'mn-native-pdf'.

Actually I made up `MN_PDF_FONT_PATH`. We don't need to keep it as long as there is a way for metanorma code to pass the exact font paths to mn2pdf. It could even be a YAML or JSON file.

**Comment by Intelligent2013** [comment]
@ronaldtse I'll add a new parameter 'fontpath' in mn2pdf command line.

**Comment by ronaldtse** [comment]
Sounds good. In this case, will we have to assume all fonts are available at that path? Or would it better to be able to specify where fonts are located by name?

e.g. 

```yaml
fonts:
  "Calibri": "path..."
  "Calibri Bold": "path..."
```

**Comment by Intelligent2013** [comment]
For fontpath parameter I mean just replacement for ${MN_PDF_FONT_PATH} variable in pdf_fonts_config.xml for paths like:
```
file://${MN_PDF_FONT_PATH}/truetype/vista/cambria.ttc
file://${MN_PDF_FONT_PATH}/truetype/msttcorefonts/arial.ttf
file://${MN_PDF_FONT_PATH}/truetype/adobe/SourceHanSans-Normal.ttc
```

All the same all fonts should be placed in these subfolder.

In any case we need pdf_fonts_config.xml config file, because it describes dependency between font file and style (bold, italic) also:
```
<font kerning="yes" embed-url="file://${MN_PDF_FONT_PATH}/truetype/vista/cambriaz.ttf">
	<font-triplet name="Cambria" style="italic" weight="bold"/>
</font>
```

**Comment by ronaldtse** [comment]
@Intelligent2013 I understand, the issue is that since we need to support multiple platforms, it is uncertain whether we can really have a font path that provides all needed fonts.

We can certainly copy out the fonts to a single location if they exist in the system, but not sure if that is the best practice.

**Comment by Intelligent2013** [comment]
@ronaldtse In the current version mn2pdf, if font can't found in specified path, then mn2pdf tries to find it in system font paths. But I see that on Mac platform there are a few system fonts like 'Arial', 'TImes New Roman', 'Courier' with another file names like 'Arial Bold Italic.ttf', 'Times New Roman Bold Italic.ttf', 'Courier New.ttf' instead of 'arialbi.ttf', 'timesbi.ttf', 'cour.ttf' specified in pdf_fonts_config.xml. I think we can add an external config file with mapping for each font file like this:
"arialbi.ttf": "Arial Bold Italic.ttf", "ArialBoldItalic.ttf"
"cour.ttf": "Courier New.ttf", "CourierNew.ttf"
...

And then, font find strategy will be:
1. If there is a font file specified in pdf_fonts_config.xml, then use it.
2. If there isn't a font file specified in pdf_fonts_config.xml, then try to find it in system font folder.
3. If there isn't a font file in system font folder, then find font file with another file name from mapping table.
4. If there isn't a font file at all, then use Source###Pro font.

In this case in MN_PDF_FONT_PATH path should be placed only a third-party fonts for platform. I.e. for Mac: Cambria, Calibri, SourceHanSans, for Linux: Arial, Times, Courier, Cambria, Calibri,SourceHanSans, for Windows: SourceHanSans only.

**Comment by Intelligent2013** [comment]
@ronaldtse I've updated mn2pdf application (https://github.com/metanorma/mn2pdf/pull/9):
- pdf_fonts_config.xml moved into .jar file, no need to specify it via cmd
- added font path parameter
- search font file with alternate name.

**Comment by Intelligent2013** [comment]
Done.
